### ISSUE TITLE
How to set function name highlight in c file

### ISSUE THREAD

**Issue by Mydynamics** [Nequo/vim-allomancer#4]
Thanks and waiting on the line

**Comment by Nequo** [comment]
Hi, you can put the following in your vimrc (from [https://vim.fandom.com/wiki/Identify_the_syntax_highlighting_group_used_at_the_cursor](url)
`map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
`
And then just press F10 to check what the highlighting is under your cursor. Then just use the same syntax as in my file or any other way of highlighting groups within vim to set the color.
